export const ACTIVEINDEX = 'ACTIVEINDEX'
export const LOADING = 'LOADING'
export const BTN_LOADING = 'BTN_LOADING'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_TOKEN = 'USER_TOKEN'
export const SET_ENTRY_KEYWORDS = 'SET_ENTRY_KEYWORDS'
export const SET_ENTRY_IDKEYWORD = 'SET_ENTRY_IDKEYWORD'
export const SET_ENTRY_STARTTIME = 'SET_ENTRY_STARTTIME'
export const SET_ENTRY_ENDTIME = 'SET_ENTRY_ENDTIME'
export const SET_ENTRY_CLICKED = 'SET_ENTRY_CLICKED'
export const SET_ACTIVE_ROUTER = 'SET_ACTIVE_ROUTER'
export const SET_MEANS_KEYWORDS = 'SET_MEANS_KEYWORDS'
export const SET_MEANS_STARTTIME = 'SET_MEANS_STARTTIME'
export const SET_MEANS_ENDTIME = 'SET_MEANS_ENDTIME'
export const SET_MEANS_ORG = 'SET_MEANS_ORG'
export const SET_MEANS_CLICKED = 'SET_MEANS_CLICKED'
export const SET_ORG_ID = 'SET_ORG_ID'
export const SET_MAIN_REPORT_CLICK = 'SET_MAIN_REPORT_CLICK'
/* 劳动列表 */
export const SET_CONTRACT_KEYWORDS = 'SET_CONTRACT_KEYWORDS'
export const SET_CONTRACT_STATUS = 'SET_CONTRACT_STATUS'
export const SET_CONTRACT_ENDDATE = 'SET_CONTRACT_ENDDATE'
export const SET_CONTRACT_CLICKED = 'SET_CONTRACT_CLICKED'

/* 干部普通审核 */
export const SET_VERIFYJOB_KEYWORD = 'SET_VERIFYJOB_KEYWORD'
export const SET_VERIFYJOB_STARTTIME = 'SET_VERIFYJOB_STARTTIME'
export const SET_VERIFYJOB_ENDTIME = 'SET_VERIFYJOB_ENDTIME'
export const SET_VERIFYJOB_CLICKED = 'SET_VERIFYJOB_CLICKED'

// 更新更正审核
export const SET_CORRECT_NAMEPHONE = 'SET_CORRECT_NAMEPHONE'
export const SET_CORRECT_STARTTIME = 'SET_CORRECT_STARTTIME'
export const SET_CORRECT_ENDTIME = 'SET_CORRECT_ENDTIME'
export const SET_CORRECT_FIELD = 'SET_CORRECT_FIELD'
export const SET_CORRECT_CLICKED = 'SET_CORRECT_CLICKED'

// 更新更正审核(营销)
export const SET_MARKET_CORRECT_NAMEPHONE = 'SET_MARKET_CORRECT_NAMEPHONE'
export const SET_MARKET_CORRECT_STARTTIME = 'SET_MARKET_CORRECT_STARTTIME'
export const SET_MARKET_CORRECT_ENDTIME = 'SET_MARKET_CORRECT_ENDTIME'
export const SET_MARKET_CORRECT_FIELD = 'SET_MARKET_CORRECT_FIELD'
export const SET_MARKET_CORRECT_CLICKED = 'SET_MARKET_CORRECT_CLICKED'

/* 劳动普通审核 */
export const SET_VERIFYCONTRACT_KEYWORD = 'SET_VERIFYCONTRACT_KEYWORD'
export const SET_VERIFYCONTRACT_STARTTIME = 'SET_VERIFYCONTRACT_STARTTIME'
export const SET_VERIFYCONTRACT_ENDTIME = 'SET_VERIFYCONTRACT_ENDTIME'
export const SET_VERIFYCONTRACT_CLICKED = 'SET_VERIFYCONTRACT_CLICKED'

export const REPORT_TABBLENAME = 'REPORT_TABBLENAME'
export const REPORT_MOVEDEPATID = 'REPORT_MOVEDEPATID'
export const REPORT_MOVEDEPATNAME = 'REPORT_MOVEDEPATNAME'
export const REPORT_MOVESTARTTIME = 'REPORT_MOVESTARTTIME'
export const REPORT_MOVEENDTIME = 'REPORT_MOVEENDTIME'

/* 社保待遇 */
export const SET_SOCIALSECURITY_KEYWORDS = 'SET_SOCIALSECURITY_KEYWORDS'
export const SET_SOCIALSECURITY_START = 'SET_SOCIALSECURITY_START'
export const SET_SOCIALSECURITY_END = 'SET_SOCIALSECURITY_END'
export const SET_SOCIALSECURITY_CLICKED = 'SET_SOCIALSECURITY_CLICKED'

/* 公积金 */
export const SET_FUND_KEYWORDS = 'SET_FUND_KEYWORDS'
export const SET_FUND_STATUS = 'SET_FUND_STATUS'
export const SET_FUND_STARTTIME = 'SET_FUND_STARTTIME'
export const SET_FUND_ENDTIME = 'SET_FUND_ENDTIME'
export const SET_FUND_CLICKED = 'SET_FUND_CLICKED'

/* 社保参保 */
export const SET_SOCIAL_KEYWORDS = 'SET_SOCIAL_KEYWORDS'
export const SET_SOCIAL_STATUS = 'SET_SOCIAL_STATUS'
export const SET_SOCIAL_NATURE = 'SET_SOCIAL_NATURE'
export const SET_SOCIAL_CLICKED = 'SET_SOCIAL_CLICKED'

/* 人才库 */
export const SET_ACCEPT_TALENT_KEYWORDS = 'SET_ACCEPT_TALENT_KEYWORDS'
export const SET_ACCEPT_TALENT_INTERVIEWVALUE = 'SET_ACCEPT_TALENT_INTERVIEWVALUE'
export const SET_ACCEPT_TALENT_CREATETIMESTART = 'SET_ACCEPT_TALENT_CREATETIMESTART'
export const SET_ACCEPT_TALENT_CREATETIMEEND = 'SET_ACCEPT_TALENT_CREATETIMEEND'
export const SET_ACCEPT_TALENT_CLICKED = 'SET_ACCEPT_TALENT_CLICKED'
export const SET_ACCEPT_TALENT_USERTID = 'SET_ACCEPT_TALENT_USERTID'
export const SET_ACCEPT_IS_DELETE = 'SET_ACCEPT_IS_DELETE'
export const SET_ACCEPT_TALENT_DEL_USERTID = 'SET_ACCEPT_TALENT_DEL_USERTID'
export const SET_ACCEPT_TALENT_PROGRESS_USERTID = 'SET_ACCEPT_TALENT_PROGRESS_USERTID'
export const SET_ACCEPT_TALENT_IDCARDNUMBER = 'SET_ACCEPT_TALENT_IDCARDNUMBER'
export const SET_ACCEPT_P_NAME = 'SET_ACCEPT_P_NAME'
export const SET_ACCEPT_DEMAND_ID = 'SET_ACCEPT_DEMAND_ID'
export const SET_ACCEPT_PARAM_ORGID = 'SET_ACCEPT_PARAM_ORGID'
export const SET_ACCEPT_PARAM_ORGNAME = 'SET_ACCEPT_PARAM_ORGNAME'
export const SET_ACCEPT_PARAM_POSTNAME = 'SET_ACCEPT_PARAM_POSTNAME'

/* 首页 */
export const SET_RECORD_NMINSURED_MSG = 'SET_RECORD_NMINSURED_MSG'

/* 邮件模板 */
export const SET_SETTING_MAIL_KEYWORDS = 'SET_SETTING_MAIL_KEYWORDS'
export const SET_SETTING_MAIL_ENABLED = 'SET_SETTING_MAIL_ENABLED'
export const SET_SETTING_MAIL_CLICKED = 'SET_SETTING_MAIL_CLICKED'

/* 审核 */
export const SET_VERIFY_ENTRY_KEYWORD = 'SET_VERIFY_ENTRY_KEYWORD'
export const SET_VERIFY_ENTRY_ID_KEYWORD = 'SET_VERIFY_ENTRY_ID_KEYWORD'
export const SET_VERIFY_ENTRY_STARTTIME = 'SET_VERIFY_ENTRY_STARTTIME'
export const SET_VERIFY_ENTRY_ENDTIME = 'SET_VERIFY_ENTRY_ENDTIME'
export const SET_VERIFY_ENTRY_CLICKED = 'SET_VERIFY_ENTRY_CLICKED'

/* 勾选树的vuex - 多选 */
export const SET_TREE_CHECKED_VAL = 'SET_TREE_CHECKED_VAL'
export const SET_TREE_CHECKED_ORGIDS = 'SET_TREE_CHECKED_ORGIDS'
export const SET_TREE_CHECKED_NAME = 'SET_TREE_CHECKED_NAME'
export const SET_TREE_CHECKED_ALL_ORGIDS = 'SET_TREE_CHECKED_ALL_ORGIDS'
/* 勾选树 - 单选 */
export const SET_SINGLE_CHECKED_ORGID = 'SET_SINGLE_CHECKED_ORGID'
export const SET_SINGLE_TREE_CHECKED_VAL = 'SET_SINGLE_TREE_CHECKED_VAL'
export const SET_SINGLE_TREE_CHECKED_NAME = 'SET_SINGLE_TREE_CHECKED_NAME'

/* 营销人员审核 */
export const SET_MARKET_VERIFY_ENTRY_KEYWORD = 'SET_MARKET_VERIFY_ENTRY_KEYWORD'
export const SET_MARKET_VERIFY_ENTRY_ID_KEYWORD = 'SET_MARKET_VERIFY_ENTRY_ID_KEYWORD'
export const SET_MARKET_VERIFY_ENTRY_STARTTIME = 'SET_MARKET_VERIFY_ENTRY_STARTTIME'
export const SET_MARKET_VERIFY_ENTRY_ENDTIME = 'SET_MARKET_VERIFY_ENTRY_ENDTIME'
export const SET_MARKET_VERIFY_ENTRY_CLICKED = 'SET_MARKET_VERIFY_ENTRY_CLICKED'

/** 员工基本信息**/
export const SET_PERSONNAL_BASE_KEYWORD = 'SET_PERSONNAL_BASE_KEYWORD'
export const SET_PERSONNAL_BASE_SEARCHORGDS = 'SET_PERSONNAL_BASE_SEARCHORGDS'
export const SET_PERSONNAL_BASE_STATUS = 'SET_PERSONNAL_BASE_STATUS'
export const SET_PERSONNAL_BASE_ENTRYDATESTART = 'SET_PERSONNAL_BASE_ENTRYDATESTART'
export const SET_PERSONNAL_BASE_ENTRYDATEEND = 'SET_PERSONNAL_BASE_ENTRYDATEEND'
export const SET_PERSONNAL_BASE_CLICKED = 'SET_PERSONNAL_BASE_CLICKED'
export const SET_PERSONNAL_BASE_STATUSSELECT = 'SET_PERSONNAL_BASE_STATUSSELECT'

/* 营销干部审核 */
export const SET_MARKETVERIFYJOB_KEYWORD = 'SET_MARKETVERIFYJOB_KEYWORD'
export const SET_MARKETVERIFYJOB_STARTTIME = 'SET_MARKETVERIFYJOB_STARTTIME'
export const SET_MARKETVERIFYJOB_ENDTIME = 'SET_MARKETVERIFYJOB_ENDTIME'
export const SET_MARKETVERIFYJOB_CLICKED = 'SET_MARKETVERIFYJOB_CLICKED'

/* 营销劳动审核 */
export const SET_MARKETVERIFYCONTRACT_KEYWORD = 'SET_MARKETVERIFYCONTRACT_KEYWORD'
export const SET_MARKETVERIFYCONTRACT_STARTTIME = 'SET_MARKETVERIFYCONTRACT_STARTTIME'
export const SET_MARKETVERIFYCONTRACT_ENDTIME = 'SET_MARKETVERIFYCONTRACT_ENDTIME'
export const SET_MARKETVERIFYCONTRACT_CLICKED = 'SET_MARKETVERIFYCONTRACT_CLICKED'

/* 营销人员审核离职审核 */
export const SET_MARKETVERIFYLEAVE_KEYWORD = 'SET_MARKETVERIFYLEAVE_KEYWORD'
export const SET_MARKETVEIFYLEAVE_STARTTIME = 'SET_MARKETVEIFYLEAVE_STARTTIME'
export const SET_MARKETVERIFYLEAVE_ENDTIME = 'SET_MARKETVERIFYLEAVE_ENDTIME'
export const SET_MARKETVERIFY_CLICKED = 'SET_MARKETVERIFY_CLICKED'

/* 营销人员调动审核 */
export const SET_MARKETVERIFYTRANSFER_ROUTESELECTS = 'SET_MARKETVERIFYTRANSFER_ROUTESELECTS'
export const SET_MARKETVERIFYTRANSFER_KEYWORD = 'SET_MARKETVERIFYTRANSFER_KEYWORD'
export const SET_MARKETVERIFYTRANSFER_STARTTIME = 'SET_MARKETVERIFYTRANSFER_STARTTIME'
export const SET_MARKETVERIFYTRANSFER_ENDTIME = 'SET_MARKETVERIFYTRANSFER_ENDTIME'
export const SET_MARKETVERIFYTRANSFER_CLICKED = 'SET_MARKETVERIFYTRANSFER_CLICKED'

/* 面包屑导航 */
export const SET_BREADCRUMB_DATA = 'SET_BREADCRUMB_DATA'

// 定义公司薪资结构设置信息的公司Id
export const SET_INFO_BY_ORG_ID = 'SET_INFO_BY_ORG_ID'

// 存储获取薪资详情的员工Id
export const SET_SALARY_ID = 'SET_SALARY_ID'
// 再次提交重新请求薪资详情接口
export const SET_SALARY_CHANGE = 'SET_SALARY_CHANGE'

// 获取当前部门有哪些津贴等福利
export const SET_CURRENT_COM__ARRAY = 'SET_CURRENT_COM__ARRAY'

// 劳动合同状态select
export const SET_CONTRACT_ALL_SELECT = 'SET_CONTRACT_ALL_SELECT'

// 公积金状态select
export const SET_FUNDALL_SELECT = 'SET_FUNDALL_SELECT'

// 社保状态select
export const SET_SOCIALL_SELECT = 'SET_SOCIALL_SELECT'

// 营销调动清空搜索条件
export const SET_CLEAR_TRANSFERSEARCH = 'SET_CLEAR_TRANSFERSEARCH'
// 获取公司还是营销还是部门
export const SET_COMPANY_TYPE = 'SET_COMPANY_TYPE'

// userOrgId获取调动部门的id
export const SET_USER_ORGID = 'SET_USER_ORGID'
// 调动的id
export const SET_TRANSFER_ORGID = 'SET_TRANSFER_ORGID'
// 高级查询的options
export const SET_DEEP_SEARCH_OPTIONS = 'SET_DEEP_SEARCH_OPTIONS'

// 员工基本导出状态
export const SET_BASE_EXPORT_STATUE = 'SET_BASE_EXPORT_STATUE'

// 薪资标准
export const SET_SALARY_STARDAND = 'SET_SALARY_STARDAND'
export const SET_TRY_SALARY_STARDAND = 'SET_TRY_SALARY_STARDAND'

// 设置保存
export const SET_SAVE1 = 'SET_SAVE1'
export const SET_SAVE2 = 'SET_SAVE2'

// 存储健康数据
export const SET_HEALTH_ARR = 'SET_HEALTH_ARR'

// 设置齿轮弹窗的出现的值
export const SET_CHOOSE_VIS = 'SET_CHOOSE_VIS'
export const SET_CHOOSE_CHECK = 'SET_CHOOSE_CHECK'
export const SET_CHOOSE_FILELIST = 'SET_CHOOSE_FILELIST'

// 设置获取薪资类型===实习期不用验证必填项‘
export const SET_CANDIDATE_TYPE = 'SET_CANDIDATE_TYPE'
// 获取是否有试用期
export const SET_PROBATION = 'SET_PROBATION'

// 储存审批角色权限数据
export const SET_CURRENT_ROLE_GROUPS = 'SET_CURRENT_ROLE_GROUPS'

// pdf文件
export const SET_PDF_FILE = 'SET_PDF_FILE'

// 所属人事主体的id
export const SET_HRBELONGID = 'SET_HRBELONGID'

// 入职详情entryDetailId
export const SET_ENTRY_DETAIL_ID = 'SET_ENTRY_DETAIL_ID'
// 入职身份证号码
export const SET_ENTRY_IDCARDNUMBER = 'SET_ENTRY_IDCARDNUMBER'
//
export const SET_INZCBEFORE = 'SET_INZCBEFORE'
export const SET_CHECKS = 'SET_CHECKS'

export const SET_CLICK_TYPE = 'SET_CLICK_TYPE'
